-- Staging Area
CREATE DATABASE ClothingSA

USE ClothingSA;
GO

DROP TABLE IF EXISTS SaleDetails;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS FabricDetails;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Stores;
DROP TABLE IF EXISTS SubCategories;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Fabrics;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Counties;
DROP TABLE IF EXISTS Countries;



CREATE TABLE Countries(
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	countryID NVARCHAR(512),
    country NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Counties (
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	countyID NVARCHAR(512),
    county NVARCHAR(512),
    countryID NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Locations (
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    locationID NVARCHAR(512),
	locationName NVARCHAR(512),
    countyID NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Fabrics (
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	fabricID NVARCHAR(512),
    fabric NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Customers (
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	customerID NVARCHAR(512),
    customerName NVARCHAR(512),
	email NVARCHAR(512),
    phoneNumber NVARCHAR(512),
    gender NVARCHAR(512), 
    locationID NVARCHAR(512), 
	size NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Categories(
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	categoryID NVARCHAR(512),
    category NVARCHAR(512),
    gender NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE SubCategories(
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	subCategoryID NVARCHAR(512),
    subCategory NVARCHAR(512),
    categoryID NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Stores(
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	storeID NVARCHAR(512),
    storeName NVARCHAR(512),
    locationID NVARCHAR(512),
	address NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Products (
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	productID NVARCHAR(512),
    productName NVARCHAR(512),
    color NVARCHAR(512),
    pattern NVARCHAR(512),
	price NVARCHAR(512),
    subcategoryID NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE FabricDetails(
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	fabricdetails NVARCHAR(512),
    fabricID NVARCHAR(512),
    productID NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE Sales(
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	saleID NVARCHAR(512),
    customerID NVARCHAR(512), 
    storeID NVARCHAR(512),
    saleDate NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);

CREATE TABLE SaleDetails(
	ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	saleDetailsID NVARCHAR(512),
	saleID NVARCHAR(512),
    productID NVARCHAR(512),
    price NVARCHAR(512),
    quantity NVARCHAR(512),
	size NVARCHAR(512),
	RecordSource NVARCHAR(10),
	EXECUTION_INSTANCE_GUID nvarchar(38) NOT NULL,
	LOAD_DATE datetime NOT NULL
);


